# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            AI Actuary
tagline:          'Pushing the limits of actuarial science'
theme: jekyll-theme-modernist
description:      'Because by the time that a textbook has been published, added to the syllabus, and you have read it, the content is already out of date'
url:              https://sdcastillo.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

google_analytics: UA-113404765-1

author:
  name:           'Sam Castillo'
  url:            

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/sdcastillo/sdcastillo.github.io
